package blocknote2md

import (
	"encoding/json"
	"os"
	"sort"
	"strings"
	"testing"
)

// goldenOrigin is the origin BlockNote's own jsdom run used for
// window.location.origin (see js/golden.test.ts).
const goldenOrigin = "http://localhost:3000"

// TestMatchesBlockNote checks Convert against the output of BlockNote's own
// blocksToMarkdownLossy for every fixture. The golden file is generated by
// js/golden.test.ts; a fixture BlockNote itself rejects is recorded as null and
// skipped here.
func TestMatchesBlockNote(t *testing.T) {
	var fixtures map[string]json.RawMessage
	var golden map[string]*string
	readJSON(t, "testdata/blocknote_fixtures.json", &fixtures)
	readJSON(t, "testdata/blocknote_golden.json", &golden)

	names := make([]string, 0, len(fixtures))
	for n := range fixtures {
		names = append(names, n)
	}
	sort.Strings(names)

	compared := 0
	for _, name := range names {
		want, ok := golden[name]
		if !ok {
			t.Errorf("fixture %q has no golden entry; regenerate with `npm run golden:update` in js/", name)
			continue
		}
		got, err := Convert(fixtures[name], WithOrigin(goldenOrigin))
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		if want == nil {
			continue // BlockNote itself rejects this input
		}
		compared++
		if got != *want {
			t.Errorf("%s:\n  got  %q\n  want %q", name, got, *want)
		}
	}
	if compared == 0 {
		t.Fatal("no fixtures were compared")
	}
	for name := range golden {
		if _, ok := fixtures[name]; !ok {
			t.Errorf("golden entry %q has no fixture", name)
		}
	}
}

func readJSON(t *testing.T, path string, v any) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(b, v); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
}

// TestFixturesAreASCII keeps the fixtures robust: invisible characters such as
// U+2028 and U+2029 must be escape sequences in the JSON, because editors and tools
// strip or normalise them when they are written raw (which once silently turned
// the line_sep fixture into plain "abc").
func TestFixturesAreASCII(t *testing.T) {
	for _, path := range []string{"testdata/blocknote_fixtures.json", "testdata/blocknote_golden.json"} {
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		for i, c := range b {
			if c >= 0x80 && path == "testdata/blocknote_fixtures.json" {
				t.Fatalf("%s has a raw non-ASCII byte at offset %d; write it as an escape sequence", path, i)
			}
		}
		for _, r := range []rune{0x2028, 0x2029, 0xFEFF} {
			if strings.ContainsRune(string(b), r) {
				t.Errorf("%s contains a raw %U; write it as an escape sequence", path, r)
			}
		}
	}
}
